### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by MichaelMonashev** [sail-sg/Adan#28]
How to install without CUDA_HOME environment variable? ~~For example https://github.com/mapillary/inplace_abn don`t ask about CUDA_HOME.~~

```
xxx@xxx:~$ python3 -m pip install git+https://github.com/sail-sg/Adan.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/sail-sg/Adan.git
  Cloning https://github.com/sail-sg/Adan.git to /tmp/pip-req-build-zs78qhzq
  Running command git clone --filter=blob:none --quiet https://github.com/sail-sg/Adan.git /tmp/pip-req-build-zs78qhzq
  Resolved https://github.com/sail-sg/Adan.git to commit 8f559205f67e565b3bea09554354d69000bd819c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-zs78qhzq/setup.py", line 5, in <module>
          cuda_extension = CUDAExtension(
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by AlexwellChen** [comment]
We didn't test to install without CUDA_HOME environment variable. Cause this is required by default when we try to install adan as a CUDA extension.

Can you try use `export CUDA_HOME=/path/to/cuda` ?

The path could use `which nvcc` command to locate. The output path might looks like `/usr/local/cuda/bin/nvcc`, then CUDA_HOME should be `/usr/local/cuda`.

**Comment by MichaelMonashev** [comment]
CUDA extension needs only for FusedAdan. How to install only pure python Adan without coping the code?

**Comment by AlexwellChen** [comment]
Understand. Currently, we are using `torch.cuda.is_available()` to judge wether install CUDA extension. 

We might need to add a manual args to enable fusion or not. 

I will fix it today later.

**Comment by AlexwellChen** [comment]
Can you try this command?

`pip install --install-option="--unfused" git+https://github.com/AlexwellChen/Adan.git`

**Comment by MichaelMonashev** [comment]
```
xxx@xxx:~$ pip3 install --install-option="--unfused" git+https://github.com/AlexwellChen/Adan.git
Defaulting to user installation because normal site-packages is not writeable
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --install-option is deprecated because it forces pip to use the 'setup.py install' command which is itself deprecated. pip 23.1 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11358
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting git+https://github.com/AlexwellChen/Adan.git
  Cloning https://github.com/AlexwellChen/Adan.git to /tmp/pip-req-build-yswhvtpn
  Running command git clone --filter=blob:none --quiet https://github.com/AlexwellChen/Adan.git /tmp/pip-req-build-yswhvtpn
  Resolved https://github.com/AlexwellChen/Adan.git to commit 962913e3bcdb58103030c1188672577b5c1062bc
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-yswhvtpn/setup.py", line 6, in <module>
          cuda_extension = CUDAExtension(
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by AlexwellChen** [comment]
Please try this again

`pip install git+https://github.com/AlexwellChen/Adan.git --install-option="--unfused"`

**Comment by MichaelMonashev** [comment]
```:~$ pip3 install git+https://github.com/AlexwellChen/Adan.git --install-option="--unfused"
Defaulting to user installation because normal site-packages is not writeable
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --install-option is deprecated because it forces pip to use the 'setup.py install' command which is itself deprecated. pip 23.1 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11358
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting git+https://github.com/AlexwellChen/Adan.git
  Cloning https://github.com/AlexwellChen/Adan.git to /tmp/pip-req-build-f9ol36qq
  Running command git clone --filter=blob:none --quiet https://github.com/AlexwellChen/Adan.git /tmp/pip-req-build-f9ol36qq
  Resolved https://github.com/AlexwellChen/Adan.git to commit 7f8a1186312a5916530235fa3d586102a7281f32
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-f9ol36qq/setup.py", line 12, in <module>
          cuda_extension = CUDAExtension(
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/xxx/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by AlexwellChen** [comment]
That's weird.

Maybe you could try to install the history branch.

Try this.

`pip install git+https://github.com/sail-sg/Adan.git@9613f61c0e780f74a17b13aa7d37eb87d0de61a7`

**Comment by MichaelMonashev** [comment]
```:~$ pip3 install git+https://github.com/sail-sg/Adan.git@9613f61c0e780f74a17b13aa7d37eb87d0de61a7
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/sail-sg/Adan.git@9613f61c0e780f74a17b13aa7d37eb87d0de61a7
  Cloning https://github.com/sail-sg/Adan.git (to revision 9613f61c0e780f74a17b13aa7d37eb87d0de61a7) to /tmp/pip-req-build-5vqynes5
  Running command git clone --filter=blob:none --quiet https://github.com/sail-sg/Adan.git /tmp/pip-req-build-5vqynes5
  Running command git rev-parse -q --verify 'sha^9613f61c0e780f74a17b13aa7d37eb87d0de61a7'
  Running command git fetch -q https://github.com/sail-sg/Adan.git 9613f61c0e780f74a17b13aa7d37eb87d0de61a7
  Running command git checkout -q 9613f61c0e780f74a17b13aa7d37eb87d0de61a7
  Resolved https://github.com/sail-sg/Adan.git to commit 9613f61c0e780f74a17b13aa7d37eb87d0de61a7
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in ./.local/lib/python3.8/site-packages (from adan==0.0.1) (1.13.1+cu117)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.8/site-packages (from torch->adan==0.0.1) (4.5.0)
Building wheels for collected packages: adan
  Building wheel for adan (setup.py) ... done
  Created wheel for adan: filename=adan-0.0.1-py3-none-any.whl size=8250 sha256=d2d7b4f15accfc5b4e6609bf2acfbc2acc83b267e465481eed8871a827befed2
  Stored in directory: /home/xxx/.cache/pip/wheels/3f/b2/c6/42cd9ca726afb02bbae34d988bb78e814bdb8bdea9a851a966
Successfully built adan
Installing collected packages: adan
Successfully installed adan-0.0.1
```

**Comment by MichaelMonashev** [comment]
But how to install Adan with new commits?

**Comment by AlexwellChen** [comment]
One way is to clone this repo and use `python setup.py install --unfused` in the repo directory to install the latest commit.

Or we have to fix the command line argument passing problem when using `pip install git+https:xxxx`, the current solution doesn't seem to work.
